version: 2
render: NetworkManager
ethernets:
  enp99s02:
    dhcp4: false
  enp105s0f0: # DMZ
    dhcp4: false
    addresses:
      - 10.1.0.12/24
    routes:
      - to: default
        via: 10.1.0.1
    nameservers:
      addresses:
        - 130.83.139.189
        - 1.1.1.1
  enp105s0f1:
  enp33s0f0:
    dhcp4: false
  enp33s0f1:
    dhcp4: false