# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp99s0:
      dhcp4: true
    enp105s0f0:
      dhcp4: false
#    enp105s0f1:
#      dhcp4: false
#      addresses:
#        - 10.100.0.8/24
#      routes:
#        - to: default
#          via: 10.100.0.4
#      nameservers:
#        addresses:
#          - 1.1.1.1
#          - 130.83.139.189
    enp33s0f0:
      dhcp4: false
    enp33s0f1:
      dhcp4: false
